version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: cd isstum && yarn && yarn run build
      - store_artifacts:
          path: /root/project/isstum/build

workflows:
  version: 2
  build:
    jobs:
      - build_windows
