version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    working_directory: ~/isstum
    steps:
      - checkout
      - run: yarn && yarn run build
      - store_artifacts:
          path: /build

workflows:
  version: 2
  build:
    jobs:
      - build_windows
